TIEMPO_INI, TIEMPO_FIN = input().split()
TIEMPO_INI = int(TIEMPO_INI)
TIEMPO_FIN = int(TIEMPO_FIN)
if TIEMPO_INI >= TIEMPO_FIN:
    TOTAL_HORAS = 24 - TIEMPO_INI + TIEMPO_FIN
else:
    TOTAL_HORAS = TIEMPO_FIN - TIEMPO_INI
print('O JOGO DUROU ' + str(TOTAL_HORAS) + ' HORA (S)')
